### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by halilyuce** [Amzd/ScrollViewProxy#1]
Hey bro, thanks for this extension but I want to use it for horizontal scrollView but I got an error. Is this not possible for use as horizontal ?

**Comment by halilyuce** [comment]
Okey, Nevermind I solved it :) It is working well, but I want to use it like this;

I have contacts above messages and when I click to any contact, I want to scroll selected items in ScrollView. I use this extension for it, but it's not scrolling inside of it. It's working when I create a button outside of scrollView but not working inside of it. Interesting :/

```
VStack{
// this button working well
            Button(action: {
                self.proxy?.scrollTo(5)
            }) {
                Text("Scroll to 5")
            }
            ScrollView { proxy in
                HStack(spacing: 15){
                    ForEach(self.viewModel.contacts.indices, id: \.self){ index in
                        Button(action: {
                            DispatchQueue.main.async {
                                self.proxy?.scrollTo(index)
                            }
                            self.viewModel.selectedUser = self.viewModel.contacts[index].user!.id
                            self.viewModel.loadMoreMessages()
                        }) {
                            ZStack(alignment: .topLeading) {
                                KFImage(URL(string: self.viewModel.contacts[index].user!.avatar!.userAvatarPathSmall()))
                                    .resizable()
                                    .aspectRatio(contentMode: .fill)
                                    .animation(.easeInOut(duration: 0.5))
                                    .frame(width: 52, height: 52)
                                    .cornerRadius(26)
                                if self.viewModel.contacts[index].unread! > 0 {
                                    ZStack {
                                        Circle()
                                            .foregroundColor(.red)
                                        Text("\(self.viewModel.contacts[index].unread!)")
                                            .foregroundColor(.white)
                                            .font(Font.system(size: 12))
                                    }.frame(width: 20, height: 20)
                                } else {
                                    EmptyView()
                                }
                            }
                        }.buttonStyle(PlainButtonStyle())
                            .id(index, scrollView: proxy)
                    }.onAppear {
                        self.proxy = proxy
                    }
                }.padding(.horizontal, 20)
            }.id(UUID().uuidString).frame(height: 76)
```

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-05 at 19 58 58](https://user-images.githubusercontent.com/29376592/86537744-10223480-befa-11ea-9393-4076c998f82d.png)

**Comment by halilyuce** [comment]
Again me :) It's working inside of scrollView too when I remove other actions. I understand it's about state variable because when I select new contact, selectedUser state is changing and it's reloading view. So, ScrollView resetting own position because of view reload. What do you recommend for it, do you have any idea ? @Amzd

**Comment by Amzd** [comment]
Cool, I didn’t think about this! Since I never tested this I don’t have a solution for it right away. I might have some time to look into this tomorrow. 

Thanks for your report!

**Comment by halilyuce** [comment]
@Amzd thanks mate :) I found a solution but it's not like what I expected. I wrapped scrollTo with DispatchQueue.main.asyncAfter but it's not smooth and looks bad.

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    self.proxy?.scrollTo(index, alignment: .leading)
}
```

**Comment by Amzd** [comment]
Hmm, does it change when you don’t call the loadMoreMessages function and don’t set the selectedUser? It might be that you are doing other changes while trying to call the scrollTo

**Comment by halilyuce** [comment]
> Hmm, does it change when you don’t call the loadMoreMessages function and don’t set the selectedUser? It might be that you are doing other changes while trying to call the scrollTo

When I don’t call loadMoreMessages() and don’t set the selectedUser, it’s working well :) But I must call these functions for get contact’s messages, If I protect scrollView postition while UI changes, it will solve this issue but I don’t have any idea for now

**Comment by Amzd** [comment]
Those functions reload the state. You can’t change the UI AND scroll, you’ll have to do one first, then the other. I don’t think this is an issue with the package so I will close this issue.

**Comment by halilyuce** [comment]
Yeah, it's not related to package but this will be a new feature if you interest. If the user selects an item in scrollView, automatically scroll to that item. What do you think ?

**Comment by Amzd** [comment]
I think you might be able to do it.

I haven’t tested it but you can use the button event to set a selected view.

Then use the View.onChange to get callback on when selected changed so then you call scrollTo.

Let me know if this solved your problem. If not, start a new issue with a more relevant title.

**Comment by halilyuce** [comment]
Thanks for suggestions mate, I don't need it anymore. I found a different solution for there now. When users select a contact, I'm moving selected contact to first order in the array. Simple and seems good :)
