### ISSUE TITLE
Performance / 100% CPU issue

### ISSUE THREAD

**Issue by nfrydenholm** [Amzd/ScrollViewProxy#10]
Hi

Thanks for providing this proxy so it's possible to scroll to specific items on iOS13 as well.

I noticed a problem when I added it to my app - as soon as I included it in a view and did the
`ScrollView { proxy in .... ` the CPU usage went to 100% while just having the view loaded on screen. (without using the proxy for anyting)

Since all the code is in one file, I copied it in (instead of doing a fork) and fixed the issue with the following if sentence in the `.introspectScrollView.`

I haven't found anything not working after that if has been added😅 

```
                .introspectScrollView {
                    if self.proxy.coordinator.scrollView != $0 {
                        self.proxy.coordinator.scrollView = $0
                        self.proxy.offset = $0.offsetPublisher
                    }
                }
```

It still feels a bit _scary_ that the `introspectScrollView` is being executed constantly, but at least this if-guard ensures that the rest of the app-state doesn't have to update.

**Comment by Amzd** [comment]
Hey, thanks! I think I created this issue with the offsetPublisher. I fixed it.

**Comment by Amzd** [comment]
Hey, thanks!
