### ISSUE TITLE
What would you do for a `LazyVStack` ?

### ISSUE THREAD

**Issue by gorbat-o** [Amzd/ScrollViewProxy#11]
Hi!
Amazing helper for iOS 13 support! thank you, appreciated here!
I was wondering, I have performance issues since i have a lot of data. I wanted to use a `LazyVStack` but I am starting to have issues like this:

```
ID (sb-l2-000021) not found, make sure to add views with `.id(_:scrollView:)`. Did find: [AnyHashable("sb-l2-000004"): (0.0, 682.4000000000001, 360.3333333333333, 168.0), AnyHashable("sb-l2-000005"): (0.0, 870.4000000000001, 370.66666666666663, 196.0), AnyHashable("sb-l2-000008"): (0.0, 1322.4, 371.0, 140.0), AnyHashable("sb-l2-000003"): (0.0, 550.4000000000001, 357.66666666666663, 112.0), AnyHashable("sb-l2-000001"): (0.0, 314.4000000000001, 358.66666666666663, 112.0), AnyHashable("sb-l2-000006"): (0.0, 1086.4, 347.66666666666663, 140.0), AnyHashable("sb-l2-000009"): (0.0, 1482.4, 365.0, 84.0), AnyHashable("sb-l2-000013"): (0.0, 2010.4, 374.0, 140.0), AnyHashable("sb-l2-000011"): (0.0, 1830.4, 310.66666666666663, 56.0), AnyHashable("sb-l2-000012"): (0.0, 1906.4, 374.0, 84.0), AnyHashable("sb-l2-000002"): (0.0, 446.4000000000001, 374.0, 84.0), AnyHashable("sb-l2-000007"): (0.0, 1246.4, 374.0, 56.0), AnyHashable("sb-l2-000010"): (0.0, 1586.4, 374.0, 224.0)]
```

I believe the fact that I am using a `LazyVStack`, it hasn't load the `Text()` with their respective ids. What do you guys recommend to do here?
Thanks for any future help!

**Comment by Amzd** [comment]
I'm unsure how the SwiftUI 2.0 implementation works for that so I can't build that into this package.

I would use the SwiftUI 2.0 ScrollViewProxy if you use lazyvstack

**Comment by gorbat-o** [comment]
I see, I am not able to use the ScrollViewProxy from Swift2.0 since i have to build for iOS 13 :/
Thanks for your help!

**Comment by Amzd** [comment]
But LazyVStack is also SwiftUI 2.0?

**Comment by gorbat-o** [comment]
You are right! But it doesn't show an error for it but for the scroll to it says that I need to be iOS 14. :/

**Comment by Amzd** [comment]
Uhhm, not sure what you mean but Apple docs say that LazyVStack is also iOS 14+ 

https://developer.apple.com/documentation/swiftui/lazyvstack

**Comment by gorbat-o** [comment]
Weird, will check that again! Thanks!

**Comment by gorbat-o** [comment]
I had a custom implementation of LazyVStack this is why! 
Totally forgot about it 😅

**Comment by Amzd** [comment]
Oh cool, I'm interested how that would work, do you have a package for this?

**Comment by gorbat-o** [comment]
It is just a wrapper that will fallback on `VStack` if `LazyVStack` is unavailable
Sorry i expressed it wrong 😂

**Comment by Amzd** [comment]
Ah, well you can make the same for ScrollViewReader

**Comment by gorbat-o** [comment]
[TempTemp.zip](https://github.com/Amzd/ScrollViewProxy/files/5859455/TempTemp.zip)

I was able to reproduce in a more isolated and sharable project.

**Comment by gorbat-o** [comment]
Quick note, this doesn't work with a `List` either. I believe it is related to the lazy loading too, since `List` (based on UITableView) is also lazy loading the content.
