### ISSUE TITLE
Scrollview inside scrollview

### ISSUE THREAD

**Issue by bharatrawal9028** [Amzd/ScrollViewProxy#15]
Hi Team,

its not working while we have put 
Scrollview inside two scrollview.

so how to solved this issue.
[OTPDemo-main.zip](https://github.com/Amzd/ScrollViewProxy/files/6500997/OTPDemo-main.zip)

Thank You,
Bharat Rawal

**Comment by Amzd** [comment]
Hey, this is a duplicate of #13 so I will close this issue

**Comment by bharatrawal9028** [comment]
Hi Team,

Please Find below video

I want scroll yellow view to top
but it's not working.

https://user-images.githubusercontent.com/20433021/118646352-b965d680-b7fd-11eb-8f8e-87829d611554.mov


Thank You,
Bharat Rawal

**Comment by Amzd** [comment]
Please post isolated code how you use ScrollViewReader. Your demo project has a lot of code. Just post as a code block in a comment here.

**Comment by bharatrawal9028** [comment]
Hi Team,

thanks for your support,

Please find below code.


Thank You,
Bharat Rawal
[ScrollViewReader.zip](https://github.com/Amzd/ScrollViewProxy/files/6501290/ScrollViewReader.zip)

**Comment by bharatrawal9028** [comment]
Hi Team,

thanks for your support,

Any update for regarding my issues.
 thanks in advance

Thank you,
bharat rawal

**Comment by Amzd** [comment]
Hello, I haven't had time to look at it yet but if you find a fix please open a PR.
