### ISSUE TITLE
coordinator.frames = []

### ISSUE THREAD

**Issue by AndrewSB** [Amzd/ScrollViewProxy#2]
I'm debugging an issue where the coordinator for the proxy has no frames, so I can't scroll to any ID.

Usage:

```swift
List {
            VStack(alignment: .leading, spacing:0) {
                Group {
                        ....
                }
            }


            ScrollViewReader {
                 ForEach(..) {
                        someView.id(someUUID)
                   }
             }
}
```

**Comment by AndrewSB** [comment]
Looks like the issue might be that my call to `id` on my cell seems to call the function in `SwiftUI`, not in this package. Aliasing the function and trying again

**Comment by Amzd** [comment]
The function is `id(_:scrollView:)` not `id(_:)`
