### ISSUE TITLE
Scrolling does not work in .onAppear { }

### ISSUE THREAD

**Issue by mdab121** [Amzd/ScrollViewProxy#8]
Hello!

Thanks for `ScrollViewProxy`, great work 👍 

I need to implement messages UI (so inverse scroll view, starting at the bottom). However using `ScrollViewProxy` in `onAppear` doesn't seem to be working correctly.

```swift
struct ContentView: View {
  var body: some View {
    ScrollView { proxy in
      VStack(spacing: 20) {
        ForEach(0..<20) { index in
          Rectangle()
            .stroke(Color.blue)
            .frame(width: 150, height: 50)
            .overlay(Text("\(index)"))
        }
      }
      .onAppear {
        proxy.scrollTo(.bottom, animated: false)
      }
    }
  }
}
```

The same **does** work correctly with Apple's `ScrollViewReader`, however that's iOS 14 only. From what I've investigated it's because the `scrollView` is not set on the coordinator at the time of the call, so it's ignored here:

```
guard let scrollView = coordinator.scrollView else { return }
```

There's a workaround to use `DispatchQueue.main.async { proxy.scrollTo(.bottom, animated: false) }`, but that's ugly and doesn't cooperate correctly with snapshot testing 😞

**Comment by Amzd** [comment]
`DispatchQueue.main.async` Is the way to do it, ~~as shown in the example in the README~~. If you’re able to reverse engineer how SwiftUI 2 gets the scrollview before its appearance I would love to hear.

Please open a new issue on your snapshot testing problems

**Comment by mdanazhiev** [comment]
Hi, I still am experiencing this issue even with the example you have provided in the readme.
`return GeometryReader { geometry in
            VStack {
                ScrollView { proxy in
                    VStack {
                        HStack {
                        //scrollTo(.bottom)
                            Button(action: { self.viewModel.proxy?.scrollTo(199) }, label: {
                                Text("Bottom")
                            })
                            Spacer()
                       //scrollTo(.center)
                            Button(action: { self.viewModel.proxy?.scrollTo(99) }, label: {
                                Text("Center")
                            })
                        }.padding()
                        
                        VStack(spacing: 20) {
                            ForEach(0..<200) { index in
                                HStack {
                                    Spacer()
                                    Text("Item: \(index)").font(.title)
                                    Spacer()
                                }.scrollId(index)
                            }
                        }
                        .zIndex(0)
                        .onAppear {
                            self.viewModel.proxy = proxy
                        }
                    }
                    
                    
                }
               
            }
        }
        .onAppear {
            if let proxy = viewModel.proxy {
                DispatchQueue.main.async { proxy.scrollTo(.bottom, animated: false) }
            }
        }
        .eraseToAnyView()`
It works perfectly with the buttons but when it comes to the onAppear it fails to scroll.
