### ISSUE TITLE
'ScrollViewProxy' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by elai950** [Amzd/ScrollViewProxy#9]
I'm gettings this error while trying to create
```
@State var proxy: ScrollViewProxy? = nil
```

Perhaps it because it shares the same name as this package but I really need to use this package instead of Apple ones.

**Comment by elai950** [comment]
Solved.
Just added
```
import struct ScrollViewProxy.ScrollViewProxy
```

**Comment by Amzd** [comment]
Using `AmzdScrollViewProxy` also fixes this. Glad you figured it out
